### ISSUE TITLE
I keep getting a parsing error

### ISSUE THREAD

**Issue by prevail90** [Clon1998/mobileraker_companion#102]
Exception:
 JRpcTimeoutError: JRpcMethod(printer.objects.query) timed out after 5 seconds

#0      JsonRpcClient.sendJRpcMethod.<anonymous closure> (package:common/network/json_rpc_client.dart:197)
#1      FutureExtensions.onError.onError (dart:async/future.dart:1082)
#2      _RootZone.runBinary (dart:async/zone.dart:1666)
#3      _FutureListener.handleError (dart:async/future_impl.dart:178)
#4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:873)
#5      Future._propagateToListeners (dart:async/future_impl.dart:894)
#6      Future._completeError (dart:async/future_impl.dart:674)
#7      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:946)
#8      TickerFuture.whenCompleteOrCancel.thunk (package:flutter/src/scheduler/ticker.dart:438)
#9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
#10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
#11     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)

**Comment by Clon1998** [comment]
Hey,
this error can happen if the timeout is to small.

Please go into the app and increase the printer timeout in the printer settings page (Open side menu -> Gear Icon -> Client Timeout)
