### ISSUE TITLE
Elegoo Neptune 4 Max

### ISSUE THREAD

**Issue by ejdprops** [Clon1998/mobileraker_companion#103]
Before I take the time and effort to try and install the companion, can anyone tell me if the Debian install will work with the Elegoo Neptune 4 Max version of Klipper?

**Comment by Clon1998** [comment]
I don't own a Neptune printer but it works fine on my Debian distribution. In any way installation via KIAUH or the installer simplifies the installation.

**Comment by MisterPl0w** [comment]
I own the Neptune 4 Plus, which has the same brains as the max. The install script worked flawlessly and the app almost immediately picked up the first notification (that the printer was in standby). So far so great!

I think this issue can be closed.

**Comment by Clon1998** [comment]
@MisterPl0w thanks for letting me know.
I'll close the issue in that case.
