### ISSUE TITLE
Mobileraker.conf cannot appear

### ISSUE THREAD

**Issue by nosoymilk** [Clon1998/mobileraker_companion#12]
hi i just finish the companion but after i restart klipper or  restart the servise thae Mobileraker.conf is not there 
is there any way to add it mantually

**Comment by Clon1998** [comment]
Hey,
AS i stated in the readme.
A config is only required if you want to configure multiple printers.
If that is the case you can create a Mobileraker.conf file in:

~/Mobileraker.conf
<mobileraker_companion DIR>/Mobileraker.conf
~/klipper_config/Mobileraker.conf

**Comment by Experte9** [comment]
Sorry to ask stupid questions, but where exactly do I need to create the config?

**Comment by Experte9** [comment]
> Hey, AS i stated in the readme. A config is only required if you want to configure multiple printers. If that is the case you can create a Mobileraker.conf file in:
> 
> * ~/Mobileraker.conf
> * <mobileraker_companion DIR>/Mobileraker.conf
> * ~/klipper_config/Mobileraker.conf

Sorry to ask stupid questions, but where exactly do I need to create the config?
I have 2 Printers on my Pi

**Comment by Clon1998** [comment]
> 

Just add it to the installation directory of mobileraker_companion

**Comment by Experte9** [comment]
Okay, I did this, but I still don't get any notifications.
