### ISSUE TITLE
Uninstall mobileraker_companion

### ISSUE THREAD

**Issue by Glenn-Kerselaers** [Clon1998/mobileraker_companion#13]
Can anyone tell me how to completely uninstall mobileraker_companion? I can only find an install script.

Thx

**Comment by Clon1998** [comment]
Just added a [remove script](https://github.com/Clon1998/mobileraker_companion/blob/main/scripts/remove-mobileraker-companion.sh). 

Just update the companion again and than you can run the remove script.
Alternatively you can also remove the service and python venv by hand.
