### ISSUE TITLE
Config file location is case sensitive

### ISSUE THREAD

**Issue by Clon1998** [Clon1998/mobileraker_companion#14]
The config file `Mobileraker.conf` should be case insensitive.
Currently, the parsing for the file only is case insensitive in `~/klipper_config/`.   
It should also allow for both `mobileraker.conf` and `Mobileraker.conf` in the locations:   
- `~/(M|m)obileraker.conf`
- `<mobileraker_companion DIR>/(M|m)obileraker.conf`

**Comment by dhruvinsh** [comment]
Is this the cause of not getting any printing notification?

**Comment by hubertron** [comment]
Which case is it expecting?

**Comment by Clon1998** [comment]
> Is this the cause of not getting any printing notification?

Most likely not.
Please make sure you're using the official build and not any beta build.

**Comment by Clon1998** [comment]
> Which case is it expecting?

I think currently it always works if you use a capital M.

**Comment by voidtrance** [comment]
Is this fixed? I had an issue with my printer's timezone, which required me to create a config file to manually specify the timezone. My config file is `~/mobileraker_companion/mobileraker.conf` and it's working.

**Comment by Clon1998** [comment]
> Is this fixed? I had an issue with my printer's timezone, which required me to create a config file to manually specify the timezone. My config file is `~/mobileraker_companion/mobileraker.conf` and it's working.

Greate!
I think I fixed it but I will leave it open for now to verify it later :)
