### ISSUE TITLE
Not working over Tailscale Network 

### ISSUE THREAD

**Issue by Martyfree123** [Clon1998/mobileraker_companion#3]
I can connect to the printer via the app perfectly over my tailscale network, but if I start a print from my PC my phone does not update with a status unless I manually open the app.

Confirmed that Mobileraker-Companion is installed and up to date.

Any ideas on how to fix?

**Comment by Clon1998** [comment]
I will close this issue since the way notifications are created changed from device created notifications to companion created notifications.
