### ISSUE TITLE
Unfortunately running mobileaker-companion.sh shows an error

### ISSUE THREAD

**Issue by Maeians** [Clon1998/mobileraker_companion#32]
Delete the original file and re-download, but run mobileaker-companion.sh encountered
root@onecloud:/home/admin/mobileraker_companion# su admin
admin@onecloud:~/mobileraker_companion$ ./scripts/install-mobileraker-companion.sh
Reading package list... Done
E: Unable to open lock file /var/lib/apt/lists/lock - open (13: Insufficient permissions)
E: Unable to lock directory /var/lib/apt/lists/
W: Error deleting file /var/cache/apt/pkgcache.bin with unlink - RemoveCaches (13: Insufficient permissions)
W: Error deleting file /var/cache/apt/srcpkgcache.bin with unlink - RemoveCaches (13: Insufficient permissions)

After I delete the file, it also shows
admin@onecloud:~/mobileraker_companion$ ./scripts/install-mobileraker-companion.sh
Reading package list... Done
E: Unable to open lock file /var/lib/apt/lists/lock - open (13: Insufficient permissions)
E: Unable to lock directory /var/lib/apt/lists/

I still can’t solve the problem after trying it. I suspect that the install-mobileker-companion.sh script is incorrect

**Comment by mkuf** [comment]
This error was introduced with yesterdays change to the install script in https://github.com/Clon1998/mobileraker_companion/pull/31.  
https://github.com/Clon1998/mobileraker_companion/pull/34 should fix this.
