### ISSUE TITLE
Multiple Printers - Mobileraker Log File Missing

### ISSUE THREAD

**Issue by fuzelet** [Clon1998/mobileraker_companion#44]
Upon doing some tests on another issue, it seems a multiple printer setup using KIAUH does not create any mobileraker.log file on the system.  When I used KIAUH and only installed one printer, I was able to find the mobileraker.log file in the ~/printer_data/ location. I have since gone back to a multiple printer setup and the mobileraker.log file does not exist in either /printer_data, /ender3_data, /ender6_data, or /tmp.  This was tested with a brand new Debian 12 install, KIAUH install, etc.  Multiple printer setup did not produce any log being created.

I used KIAUH to install two printers, named ender3 and ender6.
![Screenshot 2023-08-04 211848](https://github.com/Clon1998/mobileraker_companion/assets/70331495/12bb0c22-49f9-4d2c-a893-327644f4f81a)
![Screenshot 2023-08-04 212315](https://github.com/Clon1998/mobileraker_companion/assets/70331495/17d88b4b-b884-4c43-8561-a23dea85ac69)

Other Issue describing issue finding logs.
https://github.com/Clon1998/mobileraker_companion/issues/38

**Comment by Clon1998** [comment]
Hey, could you do me a favor and send me the content of your service file:

```bash
cat /etc/systemd/system/mobileraker.service
```

**Comment by fuzelet** [comment]
Here you go.

#Systemd service file for mobileraker
[Unit]
Description=Companion app to enable push notifications on mobileraker
After=network-online.target moonraker.service

[Install]
WantedBy=multi-user.target

[Service]
Type=simple
User=jeffrey
WorkingDirectory=/home/jeffrey/mobileraker_companion
ExecStart=/home/jeffrey/mobileraker-env/bin/python /home/jeffrey/mobileraker_companion/mobileraker.py
Restart=always
RestartSec=10

**Comment by ShaunRoberts543** [comment]
Same issue here.  I have 3 printer instances.  Printer #1 is showing on app as it should, pinter #2 and #3 still say "need companion app".  I also have not been able to locate the log file at all.  I did create a Mobileraker.conf file and it is on the #1st instance that is working, but with the other 2 listed in the file.

**Comment by Clon1998** [comment]
Hey,
I am currently not at home for another month.
However, a new/2nd printer will be available once I am back home to test this.

**Comment by Clon1998** [comment]
> Same issue here. I have 3 printer instances. Printer #1 is showing on app as it should, pinter #2 and #3 still say "need companion app". I also have not been able to locate the log file at all. I did create a Mobileraker.conf file and it is on the #1st instance that is working, but with the other 2 listed in the file.

Also could you share the mobileraker config file with me?

**Comment by Clon1998** [comment]
If you still need help feel free to reopen the issue.
