### ISSUE TITLE
not running from service file

### ISSUE THREAD

**Issue by TomW1605** [Clon1998/mobileraker_companion#47]
i just installed this but it dosnt run when using the system service. the status stays on "Activating" and it never starts
![image](https://github.com/Clon1998/mobileraker_companion/assets/17092573/2840da4a-c06a-4ceb-835a-4d5669919dc7)

when i run the command from the service file directly it works fine

**Comment by Clon1998** [comment]
Can you please run `/home/pi/mobileraker-env/bin/python --version` and verify that you are running python 3.x?

**Comment by TomW1605** [comment]
yeah its python 3.9.2
![image](https://github.com/Clon1998/mobileraker_companion/assets/17092573/fbd5a5fa-85eb-4d95-8139-9741cd095e0a)

**Comment by Clon1998** [comment]
Could you check if the app creates a `mobileraker.log` file in either `~/printer_data/logs/mobileraker.log` or in `/tmp/mobileraker.log`

**Comment by TomW1605** [comment]
running the service does not but running the python script directly does

**Comment by TomW1605** [comment]
hi, this is still an issue. while i was working on the notification stuff it wasnt much of a problem keeping a terminal open with this running since i was restarting it a lot anyway but now its getting a bit annoying. any ideas on what might be causing this? i updated to the latest version to get the rewrite stuff hoping that might fix it but it didnt

**Comment by Clon1998** [comment]
Seems to be a problem with your distro

The service errors with 217/USER


https://www.shellhacks.com/systemd-service-not-starting-status217-user/

**Comment by TomW1605** [comment]
its a stock raspberry pi os install but ill have a look and see if i can fix it from whats in the link

**Comment by TomW1605** [comment]
ok, so turns out i have been accidentally overriding the `$USER` environment variable in my dotfiles for years and somehow this is the first time its ben an issue. thanks for your help and the great app. fixed the unit file and its all working now
