### ISSUE TITLE
Disable Notifications for Timelapse Improved but still isn't fully working

### ISSUE THREAD

**Issue by Snuffy2** [Clon1998/mobileraker_companion#82]
Building on #73 and #81. As @Johnnytk36 had noted in #81, the notifications are now less when pausing and restarting to take a timelapse photo (not every layer), but are still happening, just intermittently. Often print will go 25-50% without any erroneous pause/start alerts then it will start showing these sometimes every few layers, sometimes for every layer until it completes.

If there's some type of logging you'd like to see or something to test, please let me know.

![361F4E0D-39AD-40E4-8A68-82752B440EFE_1_102_o](https://github.com/Clon1998/mobileraker_companion/assets/6526076/b875bef6-1962-41fd-adc2-7b1508fd3e78)
![76F4C8FC-64B7-4D15-8FC8-9984A6169493_1_102_o](https://github.com/Clon1998/mobileraker_companion/assets/6526076/e9d3921a-414e-49b1-97a7-ea4d3a81370d)

![61FE6747-3389-4B4E-8289-243F1DA5AA33_4_5005_c](https://github.com/Clon1998/mobileraker_companion/assets/6526076/570a0f7a-0a03-470c-94fd-2c2b69c811e2)
![34A0E374-14C2-4777-BE57-E1B25E246BD8_4_5005_c](https://github.com/Clon1998/mobileraker_companion/assets/6526076/0ecd9101-b98a-49cb-9cbd-e0f41f95a123)
![01BFC170-01AD-46F8-86E6-815204E4F049_4_5005_c](https://github.com/Clon1998/mobileraker_companion/assets/6526076/fe6979c3-2cc8-4978-96f0-b4675b727c84)
![02B23248-1B8E-4465-BE51-3693C12BE241_4_5005_c](https://github.com/Clon1998/mobileraker_companion/assets/6526076/a898a44d-fb68-45d3-86a5-f1de61ada216)
![DE03A8B9-7E6D-4A1F-A719-891F7205906F_4_5005_c](https://github.com/Clon1998/mobileraker_companion/assets/6526076/c4f60c65-6055-4376-9ff8-534ab80dd43f)

**Comment by Clon1998** [comment]
Hey,
I have ran the current version of the companion + timelapse on two of my machines without any problem.

However, I am not using the parking mode.
Can you confirm to me that you are using the parking mode?


Feel free to upload the logs. They are either located in `/tmp/mobileraker.log` or in the same location as all other logs.

**Comment by Johnnytk36** [comment]
I am using the parking mode.


<img width="969" alt="Screenshot 2024-02-22 at 12 13 14 PM" src="https://github.com/Clon1998/mobileraker_companion/assets/133730955/892bcfc0-a9f5-45a4-a51a-75d56f89947b">

**Comment by Clon1998** [comment]
> I am using the parking mode.
> 
> <img alt="Screenshot 2024-02-22 at 12 13 14 PM" width="969" src="https://private-user-images.githubusercontent.com/133730955/307103409-892bcfc0-a9f5-45a4-a51a-75d56f89947b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MzIzMTAsIm5iZiI6MTcwODYzMjAxMCwicGF0aCI6Ii8xMzM3MzA5NTUvMzA3MTAzNDA5LTg5MmJjZmMwLWE5ZjUtNDVhNC1hNTFhLTc1ZDU2Zjg5OTQ3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQyMDAwMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmJlZjMwNjgyZTQyNmI1YWI3N2YwOTA2MTllMWE5ZjRiOWQ2ZmE3OGJmYjNhYzVkMjI5NjIzMTI0ZTdjMGMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2hPDOKbnWCOHsW5cQEPBi3mnXO0B_eNjD1tPib5-zp4">

I will enable it on one of my printers to debug it!

**Comment by Snuffy2** [comment]
Same here. The parking between layers before taking the timelapse is what is triggering those notices.

**Comment by Snuffy2** [comment]
Logfile of recent print is attached. Timelapse with parking between layers is on. There were only 34 layers and it sent me Pause/Start alerts for 2 layers sometime between 25-50% complete (between layers 8-18).

[mobileraker_with_timelapse.log](https://github.com/Clon1998/mobileraker_companion/files/14518233/mobileraker_with_timelapse.log)

![646A4039-C079-42CE-B694-8F8D75769800_1_102_o](https://github.com/Clon1998/mobileraker_companion/assets/6526076/58f46a18-537f-44ed-9c13-57f45873e097)

**Comment by Snuffy2** [comment]
Any updates on getting this fixed?

**Comment by Clon1998** [comment]
> Any updates on getting this fixed?

I lost track of this issue while working on 2.7.0.
I will take a look in the next days to see if I am able to reproduce this issue and hopefully fix it.

In the meantime, can you provide me the version of the companion you are using @Snuffy2 ?

**Comment by Snuffy2** [comment]
No worries, totally understand and thank you very much for a great tool. I'm running:
Mobileraker app: 2.7.0-501
Mobileraker Companion: v0.4.0-58-g828e9a8c

**Comment by Clon1998** [comment]
> No worries, totally understand and thank you very much for a great tool. I'm running: Mobileraker app: 2.7.0-501 Mobileraker Companion: v0.4.0-58-g828e9a8c

Thanks. The companion is a bit outdated but nothing major that would affect this issue.
Also, just was able to reproduce that behavior locally. Just need to identify the root cause for this issue!

**Comment by Snuffy2** [comment]
Working great so far after printing a couple of things. Thanks!!!
