### ISSUE TITLE
After updating Klipper I'm recieving mobileraker-companion errors in Fluidd

### ISSUE THREAD

**Issue by Aiddy81** [Clon1998/mobileraker_companion#86]
After updating Klipper and moonraker I started receiving errors in the Fluidd which I have put below. I have tried removing and re-adding mobileraker but the error's still persist.

**Versions**
fluidd v1.29.0
fluidd-config v1.2.0-0-gce48c585
klipper v0.12.0-131-gd9043345
mainsail v2.10.0
mainsail-config v1.2.1-0-ge57810d5
moonraker v0.8.0-324-ga3e4dac5

**Error**
Moonraker warnings found.
[update_manager]: Failed to load extension mobileraker: Invalid path for option `install_script` in section [update_manager mobileraker]: Path `/home/biqu/mobileraker_companion/scripts/install-mobileraker-companion.sh` does not exist

Unparsed config option 'origin: https://github.com/Clon1998/mobileraker_companion.git' detected in section [update_manager mobileraker]. This may be an option no longer available or could be the result of a module that failed to load. In the future this will result in a startup error.

Unparsed config option 'primary_branch: main' detected in section [update_manager mobileraker]. This may be an option no longer available or could be the result of a module that failed to load. In the future this will result in a startup error.

Unparsed config option 'managed_services: mobileraker' detected in section [update_manager mobileraker]. This may be an option no longer available or could be the result of a module that failed to load. In the future this will result in a startup error.

**Comment by Clon1998** [comment]
Hey,
please have a look here to resolve it.

https://github.com/Clon1998/mobileraker_companion/issues/83
