### ISSUE TITLE
Unable to solve Mobileraker errors after Klipper update

### ISSUE THREAD

**Issue by fonsuak** [Clon1998/mobileraker_companion#87]
Hello, I am facing similar Moonraker issues after updating Klipper as described in the last couple of reports. But I am not being able to solve them by following #83 

The errors I get are the following: 
![image](https://github.com/Clon1998/mobileraker_companion/assets/68298108/e2ea98aa-b956-4f14-a873-6b2589222369)

My `[update_manager mobileraker]` section looks like this:
![image](https://github.com/Clon1998/mobileraker_companion/assets/68298108/5b2a824c-eb56-45d0-b46c-86c2c2ebfe2b)

I have tried changing just the `install_script` line as recommended, and also changing all lines under `[update_manager mobileraker]` to match the picture shared in #83

Before all this I also tried:

- Get everything updated via Fluidd interface (Klipper, Fluidd,  Moonraker, Mobileraker, etc.)
- Updated the RPi mcu by:
  - ssh into pi
  - `cd ~/klipper/`
  - `make menuconfig`
  - select `linux process` under `microcontroller archetecture`
  - save and exit
  - `make clean`
  - `sudo service klipper stop`
  - `make flash`
  - ` sudo service klipper start`
  
- Uninstall Mobileraker via ssh with KIAUH
- Reinstall both Moonraker and Mobileraker via ssh with KIAUH

I have run out of ideas of things to try. I would really appreciate someone giving me a hand on this.
If there is any further information/documents that I can share to investigate this please let me know.

Thank you very much

**Comment by Clon1998** [comment]
What version of moonraker are you using?
Did you try to verify that the path `/home/pi/mobileraker-env` exists in the file system via the cli?

**Comment by fonsuak** [comment]
Hello, I just finally fixed it.
Looks like after tinkering so much with this last week I left mobileraker uninstalled, reason why #83 fix was not working.
After installing mobileraker and changing `install_script: scripts/install.sh` the warnings are gone.
Issue is fixed. Thank you for the quick response and sorry for making you lose time.

**Comment by Clon1998** [comment]
> Hello, I just finally fixed it. Looks like after tinkering so much with this last week I left mobileraker uninstalled, reason why #83 fix was not working. After installing mobileraker and changing `install_script: scripts/install.sh` the warnings are gone. Issue is fixed. Thank you for the quick response and sorry for making you lose time.

No worries!
