### ISSUE TITLE
Duplicated notifications. iOS

### ISSUE THREAD

**Issue by wikolii** [Clon1998/mobileraker_companion#88]
Hi, since some time ago i'm getting duplicated notifications on iphone. I can't pinpoint the exact moment it changed, sorry.
Here's the last log from the app:
[mobileraker_2024-04-06T18-29-21.log](https://github.com/Clon1998/mobileraker_companion/files/14905761/mobileraker_2024-04-06T18-29-21.log)

Thanks!

**Comment by Clon1998** [comment]
Hey,
this can happen if you ever re-added a printer.
Did you try to clear the notification registry of the printer within the app?
To do that, open the settings of the printer in the app and at the very bottom of the page the app should offer a button to clear the registry.

**Comment by wikolii** [comment]
That seems to have worked. Thanks!
