### ISSUE TITLE
Newbie has errors on Neptune 4 Pro

### ISSUE THREAD

**Issue by UrsuMare** [Clon1998/mobileraker_companion#97]
Hello, 
I was given a Neptune 4 Pro and a link that helped me configure the LAN connection. I am total new to Klipper and to Github, never got the hang of it, it's not intuitive for me so please have patience.

On the home page I have some errors. One of them I managed to solve following a discussion (issue 83) here, but I'm stuck with the rest:

Moonraker warnings found.
[update_manager]: Failed to load extension display: Invalid path for option `path` in section [update_manager display]: Path `/home/mks/display_connector` does not exist
Unparsed config option 'primary_branch: ' detected in section [update_manager display]. This may be an option no longer available or could be the result of a module that failed to load. In the future this will result in a startup error.
Unparsed config option 'virtualenv: /home/mks/display_connector/venv' detected in section [update_manager display]. This may be an option no longer available or could be the result of a module that failed to load. In the future this will result in a startup error.
Unparsed config option 'requirements: requirements.txt' detected in section [update_manager display]. This may be an option no longer available or could be the result of a module that failed to load. In the future this will result in a startup error.
Unparsed config option 'origin: https://github.com/OpenNeptune3D/display_connector.git' detected in section [update_manager display]. This may be an option no longer available or could be the result of a module that failed to load. In the future this will result in a startup error.

The printer is printing fine, but those errors annoy me so I decided to get them solved.

**Comment by Clon1998** [comment]
Please see: 
https://github.com/Clon1998/mobileraker_companion/issues/83#issuecomment-2217960466
